import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <Navbar className=""/>
          <div className="flex-1 transition-all duration-300 ease-in-out px-6 md:px-12 lg:px-24 flex items-center justify-center">
            {children}</div>
        </div>
      </body>
    </html>
  );
}
